(load "alignment_path.clp")
(bind ?*path* (str-cat ?*path* "/clp_files/get_clause_info.clp"))
(load ?*path*)
(load-facts "E_constituents_info.dat")
(load-facts "Node_category.dat")
(watch rules)
(watch facts)
(agenda)
(run)
(save-facts "clause_info.dat" local clause_boundry_head-childs)
(clear)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(load "alignment_path.clp")
(bind ?*path* (str-cat ?*path* "/clp_files/get_clause_info_in_hindi.clp"))
(load ?*path*)
(load-facts "verb_root_tam_info.dat")
(load-facts "anchor_tmp.dat")
;(load-facts "manual_id_mapped.dat")
(watch rules)
(watch facts)
(agenda)
(run)
(save-facts "hnd_clause_info.dat" local hnd_clause_hid-childs)
(clear)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(load "alignment_path.clp")
(bind ?*path* (str-cat ?*path* "/clp_files/heuristics.clp"))
(load ?*path*)
;(load-facts "H_wordid-word_mapping.dat")
(load-facts "manual_id_mapped.dat")
(load-facts "cat_consistency_check.dat")
(load-facts "word.dat")
(load-facts "relations.dat")
(watch rules)
(watch facts)
(agenda)
(run)
(save-facts "new_p_layer_tmp.dat" local P1_tmp eng_id_decided hid_id_decided)
(clear)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(load "alignment_path.clp")
(bind ?path1 (str-cat ?*path* "/clp_files/group_kriyA_mUla.clp"))
(load ?path1)
(bind ?path2 (str-cat ?*path* "/clp_files/decide_anchor_type.clp"))
(load ?path2)
(load-facts "hindi_meanings_with_grp_ids.dat")
(load-facts "cat_consistency_check.dat")
(load-facts "revised_root.dat")
(load-facts "E_grouping.dat")
(load-facts "H_grouping.dat")
;(load-facts "H_wordid-word_mapping.dat")
(load-facts "manual_id_mapped.dat")
(load-facts "kriyA_mUla_info.dat")
(load-facts "new_p_layer_tmp.dat")
(load-facts "E_grouping_wrd.dat")
(load-facts "H_grouping_wrd.dat")
(load-facts "verb_root_tam_info.dat")
(load-facts "anchor_tmp.dat")
(load-facts "manual_mapped_id_root_info.dat")
(assert (no_match_found))
(assert (repeated_ids))
(watch rules)
(watch facts)
(agenda)
(run)
(save-facts "E_grouping1.dat" local Eng_label-group_elements)
(save-facts "H_grouping1.dat" local Hnd_label-group_elements)
(save-facts "new_p_layer_tmp1.dat" local P1_tmp eng_id_decided hid_id_decided)
(save-facts "E_grouping_wrd1.dat" local Eng_label-group_words)
(save-facts "H_grouping_wrd1.dat" local Hnd_label-group_words)
(save-facts "anchor.dat" local iter-type-eng_g_id-h_g_id hindi_head_id-grp_ids iter-h_g_id no_match_found repeated_ids)
(clear)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(load "alignment_path.clp")
(bind ?path1 (str-cat ?*path* "/clp_files/get_anchor.clp"))
(load ?path1)
(bind ?path2 (str-cat ?*path* "/clp_files/decide_anchor_type.clp"))
(load ?path2)
(load-facts "new_p_layer_tmp1.dat")
(load-facts "anchor.dat")
(load-facts "E_grouping1.dat")
(load-facts "H_grouping1.dat")
(watch rules)
(watch facts)
(agenda)
(run)
(save-facts "anchor1.dat" local iter-type-eng_g_id-h_g_id hindi_head_id-grp_ids iter-h_g_id no_match_found repeated_ids)
(clear)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(load "alignment_path.clp")
(bind ?path1 (str-cat ?*path* "/clp_files/align_using_dic.clp"))
(load ?path1)
(bind ?path2 (str-cat ?*path* "/clp_files/decide_anchor_type.clp"))
(load ?path2)
(load-facts "anchor1.dat")
(load-facts "database_mng.dat")
(load-facts "manual_id_mapped.dat")
(load-facts "revised_root.dat")
;(load-facts "eng_conll_root.dat")
(load-facts "eng_std_facts.dat")
(load-facts "manual_mapped_id_root_info.dat")
(load-facts "E_grouping1.dat")
(load-facts "H_grouping1.dat")
(load-facts "anu_root.dat")
(load-facts "cat_consistency_check.dat")
(watch rules)
(watch facts)
(agenda)
(run)
(save-facts "anchor2.dat" local iter-type-eng_g_id-h_g_id hindi_head_id-grp_ids iter-h_g_id no_match_found repeated_ids)
(clear)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(load "alignment_path.clp")
(bind ?path1 (str-cat ?*path* "/clp_files/align_using_parser.clp"))
(load ?path1)
(bind ?path2 (str-cat ?*path* "/clp_files/decide_anchor_type.clp"))
(load ?path2)
(load-facts "anchor2.dat")
(load-facts "E_grouping1.dat")
(load-facts "H_grouping1.dat")
;(load-facts "eng_conll_facts.dat")
(load-facts "eng_std_facts.dat")
(load-facts "hnd_conll_facts.dat")
(watch rules)
(watch facts)
(agenda)
(run)
(save-facts "anchor3.dat" local iter-type-eng_g_id-h_g_id hindi_head_id-grp_ids iter-h_g_id no_match_found repeated_ids)
(clear)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(load "alignment_path.clp")
(bind ?path1 (str-cat ?*path* "/clp_files/align_thru_clause_boundry.clp"))
(load ?path1)
(bind ?path2 (str-cat ?*path* "/clp_files/decide_anchor_type.clp"))
(load ?path2)
(load-facts "anchor3.dat")
(load-facts "eng_parent_sanwawi.dat")
(load-facts "hnd_parent_sanwawi.dat")
(load-facts "H_grouping1.dat")
(load-facts "E_grouping1.dat")
(load-facts "E_grouping_wrd1.dat")
(load-facts "H_grouping_wrd1.dat")
(load-facts "manual_id_mapped.dat")
(load-facts "original_word.dat")
(load-facts "word.dat")
;(load-facts "eng_conll_facts.dat")
(load-facts "eng_std_facts.dat")
(load-facts "hnd_conll_facts.dat")
(load-facts "transliterate_wrds.dat")
(load-facts "revised_root.dat")
(load-facts "database_mng.dat")
(load-facts "tam_info.dat")
(load-facts "verb_root_tam_info.dat")
(load-facts "clause_info.dat")
(watch rules)
(watch facts)
(agenda)
(run)
(save-facts "anchor4.dat" local iter-type-eng_g_id-h_g_id hindi_head_id-grp_ids iter-h_g_id no_match_found repeated_ids)
(clear)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(load "alignment_path.clp")
(bind ?path1 (str-cat ?*path* "/clp_files/correct_hnd_grouping.clp"))
(load ?path1)
(bind ?path2 (str-cat ?*path* "/clp_files/decide_anchor_type.clp"))
(load ?path2)
(load-facts "anchor4.dat")
(load-facts "repeated_ids.dat")
(load-facts "E_grouping1.dat")
(load-facts "H_grouping1.dat")
(load-facts "word.dat")
(load-facts "manual_id_mapped.dat")
(load-facts "eng_wrd_occurence.dat")
(load-facts "hnd_wrd_occurence.dat")
(watch rules)
(watch facts)
(agenda)
(run)
(save-facts "anchor5.dat" local iter-type-eng_g_id-h_g_id hindi_head_id-grp_ids iter-h_g_id no_match_found repeated_ids)
(clear)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(load "alignment_path.clp")
(bind ?path1 (str-cat ?*path* "/clp_files/heuristic1.clp"))
(load ?path1)
(bind ?path2 (str-cat ?*path* "/clp_files/decide_anchor_type.clp"))
(load ?path2)
(load-facts "anchor5.dat")
(load-facts "hindi_meanings_with_grp_ids.dat")
(load-facts "manual_id_mapped.dat")
(load-facts "hindi_id_order.dat")
(load-facts "H_grouping1.dat")
(load-facts "database_mng.dat")
(load-facts "revised_root.dat")
;(load-facts "eng_conll_root.dat")
(load-facts "eng_std_facts.dat")
(load-facts "manual_mapped_id_root_info.dat")
(load-facts "manual_lwg_new.dat")
(load-facts "word_alignment.dat")
(load-facts "manual_id_wrdid.dat")
(load-facts "id_Apertium_output.dat")
(load-facts "multi_word_expressions.dat")
(watch rules) 
(watch facts)
(agenda)
(run)
(save-facts "anchor6.dat" local iter-type-eng_g_id-h_g_id hindi_head_id-grp_ids iter-h_g_id no_match_found repeated_ids)
(save-facts "H_grouping2.dat" local Hnd_label-group_elements)
(clear)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(load "alignment_path.clp")
(bind ?*path* (str-cat ?*path* "/clp_files/generate_new_layer.clp"))
(load ?*path*)
(load-facts "anchor6.dat")
(assert (label P2))
(watch rules)
;(watch facts)
(agenda)
(run)
(save-facts "new_layer_p2.dat" local dummy )
(clear)
(exit)
