(load "alignment_path.clp")
(bind ?path1 (str-cat ?*path* "/clp_files/align_using_mul_nmt.clp"))
(load ?path1)
(bind ?path2 (str-cat ?*path* "/clp_files/decide_anchor_type.clp"))
(load ?path2)
(load-facts "anchor6.dat")
(load-facts "manual_id_mapped.dat")
(load-facts "mul_nmt_facts.dat")
(watch rules)
(watch facts)
(agenda)
(run)
(save-facts "anchor7.dat" local iter-type-eng_g_id-h_g_id hindi_head_id-grp_ids iter-h_g_id no_match_found repeated_ids)
(clear)
;------------------------------------------------------------------------------------------
(load "alignment_path.clp")
(bind ?*path* (str-cat ?*path* "/clp_files/generate_new_layer.clp"))
(load ?*path*)
(load-facts "anchor7.dat")
(assert (label P3))
(watch rules)
(watch facts)
(agenda)
(run)
(save-facts "new_layer_p3.dat" local dummy )
(clear)
(exit)
