(load "alignment_path.clp")
(bind ?path (str-cat ?*path* "/clp_files/group_vib.clp"))
(load ?path)
(load-facts "hnd_clause_word.dat")
(load-facts "clause_anchor_tmp.dat")
(watch rules)
(watch facts)
(agenda)
(run)
(save-facts "clause_anchor.dat" local hindi_head_id-grp_ids iter-h_g_id)
(clear)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(load "alignment_path.clp")
(bind ?path (str-cat ?*path* "/clp_files/map.clp"))
(load ?path)
(load-facts "mwe_clause.dat")
(load-facts "eng_clause_word.dat")
(load-facts "hnd_clause_word.dat")
(load-facts "clause_anchor.dat")
(load-facts "map_clause_ids.dat")
(watch rules)
(watch facts)
(agenda)
(run)
(save-facts "mwe_clause_mapped.dat" local ids-cmp_mng-head-cat-mng_typ-priority ids-domain_cmp_mng-head-cat-mng_typ-priority iter-h_g_id)
(clear)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(load "alignment_path.clp")
(bind ?path (str-cat ?*path* "/clp_files/align.clp"))
(load ?path)
(load-facts "transliterate_wrds.dat")
(load-facts "eng_clause_word.dat")
(load-facts "hnd_clause_word.dat")
(load-facts "clause_anchor.dat")
(load-facts "mwe_clause_mapped.dat")
(load-facts "clause_align_data.dat")
(watch rules)
(watch facts)
(agenda)
(run)
(save-facts "anchor_clause.dat" local iter-type-eng_g_id-h_g_id hindi_head_id-grp_ids iter-h_g_id)
(clear)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(load "alignment_path.clp")
(bind ?path (str-cat ?*path* "/clp_files/clause_sugg.clp"))
(load ?path)
(load-facts "eng_clause_word.dat")
(load-facts "hnd_clause_word.dat")
(load-facts "clause_anchor.dat")
(load-facts "anchor_clause.dat")
(watch rules)
(watch facts)
(agenda)
(run)
(save-facts "anchor_clause1.dat" local iter-type-eng_g_id-h_g_id hindi_head_id-grp_ids iter-h_g_id)
(save-facts "mng_suggested.dat" local meaning_suggested)
(clear)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(load "alignment_path.clp")
(bind ?*path* (str-cat ?*path* "/clp_files/generate_new_layer.clp"))
(load ?*path*)
(load-facts "anchor_clause1.dat")
(load-facts "mng_suggested.dat")
(assert (label P2_clause))
(watch rules)
(watch facts)
(agenda)
(matches replace_head_with_childs)
(facts) 
(run)

(save-facts "new_layer_clause.dat" local dummy)
(clear)
(exit)


